# Generated by Django 3.1.6 on 2021-03-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motifs',
            fields=[
                ('sequence', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinMotifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motif_database.motifs')),
            ],
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('label', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('sequence', models.TextField(max_length=10000)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('motifs', models.ManyToManyField(through='motif_database.ProteinMotifs', to='motif_database.Motifs')),
            ],
        ),
        migrations.AddField(
            model_name='proteinmotifs',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motif_database.proteins'),
        ),
    ]
