# Generated by Django 3.1.6 on 2021-03-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motif_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteins',
            old_name='full_name',
            new_name='name',
        ),
    ]
