# Generated by Django 3.1.6 on 2021-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteins',
            name='organism',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
