# Generated by Django 3.1.6 on 2021-03-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif_database', '0002_auto_20210309_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteins',
            name='organism',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
