# Generated by Django 3.1.6 on 2021-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif_database', '0003_proteins_organism'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteins',
            name='label',
        ),
        migrations.AlterField(
            model_name='proteins',
            name='name',
            field=models.CharField(default='', max_length=1000, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proteins',
            name='sequence',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
