# Generated by Django 3.1.6 on 2021-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif_database', '0004_auto_20210309_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteins',
            name='sequence',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
