# Generated by Django 3.1.6 on 2021-03-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motif_database', '0007_auto_20210309_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteinmotifs',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='proteinmotifs',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='proteins',
            name='motifs',
        ),
        migrations.DeleteModel(
            name='Motifs',
        ),
        migrations.DeleteModel(
            name='ProteinMotifs',
        ),
        migrations.DeleteModel(
            name='Proteins',
        ),
    ]
